version: '2'

services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: backend.Dockerfile
  #   ports:
  #     - '8480:3002'
  #   volumes:
  #     - ./prisma/dev.db:/app/prisma/dev.db
  #     - ./prisma/session.db:/app/prisma/session.db
  #   depends_on:
  #     - minio
  #   links:
  #     - minio

  minio:
    image: 'minio/minio:latest'
    ports:
      - '8380:9000'
      - '8381:9001'
    volumes:
      - ./data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_SERVICE_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_SERVICE_ROOT_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=${MINIO_SERVICE_BUCKET_NAME}
    command: server /data -console-address ":9001"
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    ports:
      - 8280:8978
    volumes:
      - ./prisma/dev.db:/opt/cloudbeaver/localdb/dev.db
      - ./prisma/session.db:/opt/cloudbeaver/localdb/session.db
      - cloudbeaver_data:/opt/cloudbeaver/workspace

volumes:
  cloudbeaver_data:
