export enum ViewCode {
  GREETINGS_VIEW = 'GREETINGS_VIEW',
  EMPTY_CATEGORY_VIEW = 'EMPTY_CATEGORY_VIEW',
  DEFAULT_CATEGORY_VIEW = 'DEFAULT_CATEGORY_VIEW',
  EMPTY_GAME_SEARCH_RESULTS_VIEW = 'EMPTY_GAME_SEARCH_RESULTS_VIEW',
  GAME_SEARCH_RESULTS_VIEW = 'GAME_SEARCH_RESULTS_VIEW',
  FEEDBACK_VIEW_BEFORE = 'FEEDBACK_VIEW_BEFORE',
  FEEDBACK_VIEW_AFTER = 'FEEDBACK_VIEW_AFTER',
  CATEGORY_SELECTION_VIEW = 'CATEGORY_SELECTION_VIEW',
}
